title: Pritam
logo:  # you can add own logo.
description: I am a Content Writer/Editor, living in Bangalore! I have been writing ever since I remember! I also like Art and Photography. I work at an AI-powered edtech, revolutionizing education. I am also learning to code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Pritam
  image: '/assets/img/08.jpg'
  job: I am a Content Writer/Editor, living in Bangalore! 
  bio: I have been writing ever since I remember! I also like art and photography. I work at an AI-powered edtech, revolutionizing education. I am also learning to code.
  email: hello@pritam.io


# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/prritam
  - name: Facebook
    link: https://www.facebook.com/prritam
  - name: LinkedIn
    link: https://www.linkedin.com/in/pritamtheargumentativeyouth/
  - name: Instagram
    link: https://www.instagram.com/murphyable/


# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: :title/
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
